#pragma once

#define MOUSE_SENSIBILITY 6.f
#define BORDER_SIZE 100.f
#define FOV_MOUVEMENT_SCALING 6.f
#define ACCELERATION_TIME 3.f
#define ROTATION_ACCELERATION_TIME 1.5f

enum OjectsID {
	SPACESHIP,
	ASTERO,
	ALLY_ROCKET,
	ENEMY_ROCKET,
	BORDER,
	ENEMY

};